### ISSUE TITLE
Build Docker Image for Arm64v8 

### ISSUE THREAD

**Issue by helkaroui** [EventStore/EventStore#2380]
I was trying to build docker image for an arm64v8 architecture. I got this error: 
I followed these steps: 

1- I edited the docker file with the proper base image and arguments:

```
ARG CONTAINER_RUNTIME=bionic-arm64v8
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic-arm64v8 AS build
ARG RUNTIME=linux-arm

WORKDIR /build/ci

COPY ./ci ./

WORKDIR /build/src

COPY ./src/EventStore.sln ./src/*/*.csproj ./src/Directory.Build.* ./

RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done

RUN dotnet restore --runtime=${RUNTIME}

COPY ./src .

RUN dotnet build --configuration=Release --runtime=${RUNTIME} --no-restore --framework=netcoreapp3.1

FROM build as test
ARG RUNTIME=linux-arm
RUN echo '#!/usr/bin/env sh\n\
cp /build/src/EventStore.Core.Tests/Services/Transport/Tcp/test_certificates/ca/ca.crt /usr/local/share/ca-certificates/ca_eventstore_test.crt\n\
update-ca-certificates\n\
find /build/src -maxdepth 1 -type d -name "*.Tests" -print0 | xargs -I{} -0 -n1 bash -c '"'"'dotnet test --configuration Release --blame --settings /build/ci/ci.runsettings --logger:html --logger:trx --logger:"console;verbosity=normal" --results-directory=/build/test-results/$1 $1'"'"' - '"'"'{}'"'"'\n\
echo $(find /build/test-results -name "*.html" | xargs cat) > /build/test-results/test-results.html' \
    >> /build/test.sh && \
    chmod +x /build/test.sh
CMD ["/build/test.sh"]

FROM build as publish
ARG RUNTIME=linux-arm

RUN dotnet publish --configuration=Release --runtime=${RUNTIME} --self-contained \
     --framework=netcoreapp3.1 --output /publish /p:PublishTrimmed=true EventStore.ClusterNode

FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.1-${CONTAINER_RUNTIME} AS runtime
ARG UID=1000
ARG GID=1000

RUN apt update && \
    apt install -y \
    curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/eventstore

RUN addgroup --gid ${GID} "eventstore" && \
    adduser \
    --disabled-password \
    --gecos "" \
    --ingroup "eventstore" \
    --no-create-home \
    --uid ${UID} \
    "eventstore"

COPY --from=publish /publish ./

RUN mkdir -p /var/lib/eventstore && \
    chown -R eventstore:eventstore /opt/eventstore /var/lib/eventstore

USER eventstore

VOLUME /var/lib/eventstore

EXPOSE 1112/tcp
EXPOSE 1113/tcp
EXPOSE 2112/tcp
EXPOSE 2113/tcp

HEALTHCHECK --interval=5s --timeout=5s --retries=24 \
    CMD curl --fail --insecure https://localhost:2113/health/live || exit 1

ENTRYPOINT ["/opt/eventstore/EventStore.ClusterNode"]
CMD ["--ext-ip", "0.0.0.0", "--int-ip", "0.0.0.0"]
```

2- Activated docker buildx command for cross platform compilation, then build the image: 
`docker buildx build --platform linux/arm64 .`

I got this message: 
``` Error
error NETSDK1032: The RuntimeIdentifier platform 'linux-arm' and the PlatformTarget 'x64' must be compatible.
```
Anyone could help ?

**Comment by pgermishuys** [comment]
The error you are receiving is because `x64` is `x86-x64` and you are trying to build for `ARM`. To be able to build Event Store you would also need to adjust the currently set platforms to include `Any CPU` in the `csproj` files.

Unfortunately, at present, the grpc tools doesn't support ARM (https://github.com/grpc/grpc/issues/22263).

You can get around the grpc tools issue by building on a grpc tools supported platform and targeting the `linux-arm64` runtime via `dotnet build`.
e.g.
```
dotnet build -c Release -r linux-arm64 /p:Platform="Any CPU" src/
```

As a side note, there are no plans to support building for `ARM` directly from a repo clone.

**Comment by JacobT14** [comment]
Just want to bring this back from the dead a little bit... Currently just got a new M1 Macbook Air and it seems like maybe I should be able to work around this issue, but can't seem to figure it out.  Has anyone been able to successfully run EventStore on an M1 chip?

**Comment by ylorph** [comment]
We'll have to wait for https://github.com/grpc/grpc/issues/22263#issuecomment-682351109 to be solved

**Comment by ylorph** [comment]
https://github.com/grpc/grpc/milestone/56

**Comment by eunmin** [comment]
gRPC issuss(rpc/grpc#22263) seems to have been resolved.
Could you try it again?

**Comment by oskardudycz** [comment]
We released an alpha version of the ARM64 image. We're still testing it, but it looks promising!

You have to use the GitHub Container registry image: https://github.com/EventStore/EventStore/pkgs/container/eventstore/7973829.

Docker image: `ghcr.io/eventstore/eventstore:20.6.1-alpha.0.69-arm64v8`

Example how to run the command:

```
docker run --name esdb-node -it -p 2113:2113 -p 1113:1113 \
    ghcr.io/eventstore/eventstore:20.6.1-alpha.0.69-arm64v8 --insecure --run-projections=All \
    --enable-external-tcp --enable-atom-pub-over-http
```

You can also subscribe to PR https://github.com/EventStore/EventStore/pull/3076 to see the progress on the ARM64 build.

**Comment by ecwyne** [comment]
@oskardudycz, worked for me on Apple M1 like a charm! Thanks so much!

**Comment by oskardudycz** [comment]
@ecwyne, great! If you noticed any unexpected behaviour, we'd be grateful for the feedback.

I'll keep this ticket open until the regular ARM64 release is available 👍

**Comment by wSedlacek** [comment]
The alpha image is working great on my M1 Max! Thank you!

**Comment by AlexandreDecollas** [comment]
Very great job! Works quite well on my M1 too, thank you very much! 
Is there a way I can find other versions of the image? a alpha repo or something? I'm currently searching a v5.0.9 image. If there are no repo, could you please build and share such a version?

**Comment by oskardudycz** [comment]
@AlexandreDecollas, unfortunately, v5 is out of support at the end of the year, plus adding ARM support required quite of an effort, and making that work on v5 would be even harder.

**Comment by oskardudycz** [comment]
`21.10.0-alpha-arm64v8` docker image is available here: https://github.com/EventStore/EventStore/pkgs/container/eventstore/11006179?tag=21.10.0-alpha-arm64v8. It's a first build that's built directly from source code, without non-experimental binaries. 

We hope to provide a non-alpha release in the following database version. I'll keep this issue open till now, but so far, so good. We're not aware of any specific ARM issues for this build. If you found any, we'd be grateful for the information.

**Comment by purefun** [comment]
```sh
docker run -p 1113:1113 -p 2113:2113 ghcr.io/eventstore/eventstore:21.10.1-alpha-arm64v8 --insecure
```

**Comment by raarts** [comment]
I see that 21.10.2 is the most recent available.

**Comment by jakzal** [comment]
Is there anything we can do to help push a non-alpha release?

I've been using the alpha version of the arm image on my M1 Mac for the past month and found no issues so far.

**Comment by jakzal** [comment]
For those who use testcontainers and need to run their tests on multiple architectures, just use the default image in your tests:

```java
 private static final GenericContainer eventStoreDb = new GenericContainer(DockerImageName.parse("ghcr.io/eventstore/eventstore:21.10.8-preview1-alpine"))
      .withExposedPorts(2113)
      .withEnv("EVENTSTORE_INSECURE", "true");
```

Then, create an image name substitutor to replace it when tests are run on M1 Mac:

```java
package com.kaffeinelabs.journal.eventstoredb.testcontainers;

import org.testcontainers.utility.DockerImageName;
import org.testcontainers.utility.ImageNameSubstitutor;

public class EventStoreImageNameSubstitutor extends ImageNameSubstitutor {
  private static final String ARM_IMAGE = "ghcr.io/eventstore/eventstore:21.10.8-alpha-arm64v8";

  @Override
  public DockerImageName apply(final DockerImageName original) {
    if (isEventStoreImage(original) && isRunOnAppleSilicon()) {
      return DockerImageName.parse(ARM_IMAGE);
    }

    return original;
  }

  @Override
  protected String getDescription() {
    return "Substitutes EventStoreDB image name if run on Apple silicon.";
  }

  private static boolean isRunOnAppleSilicon() {
    return "aarch64".equals(System.getProperty("os.arch", "unknown"));
  }

  private static boolean isEventStoreImage(final DockerImageName original) {
    return "ghcr.io/eventstore/eventstore".equals(original.getUnversionedPart());
  }
}
```

Register the image name substitutor in `src/test/resources/testcontainers.properties`:

```properties
image.substitutor=com.kaffeinelabs.journal.eventstoredb.testcontainers.EventStoreImageNameSubstitutor
```

**Comment by arwinneil** [comment]
Hey @jakzal, one of the main things that was holding up a non-alpha release was moving the database to .NET 6 as it brings significant stability and performance improvements on ARM. This was recently done in https://github.com/EventStore/EventStore/pull/3595, so slowly but steadily moving towards a non-alpha release! Cheers!

**Comment by jokesterfr** [comment]
It would be really handy to have a single docker tag, supporting both x86_64 and arm64 :)
Same as above, not experiencing any crash on M1 since months, seems stable so far.

**Comment by arwinneil** [comment]
@jokesterfr Thanks for the feedback, glad to hear that. The plan is to have 1 single multi-architecture image once we officially support ARM64. 😄

**Comment by mohammadsaadshafiq** [comment]
Hi, I wrote an article to make it look easy.
https://medium.com/@saad.shafiq1997/how-to-locally-set-up-an-event-store-usi-9c909d7a5603

**Comment by alexeyzimarev** [comment]
[DB-27](https://linear.app/eventstore/issue/DB-27/build-an-arm64-package)

**Comment by jbpros** [comment]
> @jokesterfr Thanks for the feedback, glad to hear that. The plan is to have 1 single multi-architecture image once we officially support ARM64. 😄

Hi,

Is that happening any time soon? Thanks!

**Comment by alexeyzimarev** [comment]
Not yet. It is planned, but it's more tricky than we originally thought, and we have some things with higher priority right now.

**Comment by jbpros** [comment]
Alright, thanks for the quick response!

**Comment by itgram** [comment]
I would like to share with you something I did before related to some limits to building 1 image for multiple arch
maybe it can help

```yaml
name: DevContainers Publish

concurrency: devcontainers-publish

on:
  release:
    branches: [main]
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_PLATFORM: linux/amd64,linux/arm64

jobs:
  build-and-push:
    name: DevContainer Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image: [base, base-slim]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change some of github variables to lowercase
        run: echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      # Get the semantic release version tags
      - name: Get the semantic release version tags
        uses: actions/github-script@v7
        with:
          script: |
            const branchParts = context.ref.split('/')
            var version = branchParts.pop()
            if (version[0] == "v") {
              version = version.substring(1)
            }
            parts = version.split(".")
            if (parts.length != 3) {
              core.setFailed(`Error invalid semantic versioning of release tag name`)
            }
            core.exportVariable("MAJOR_VERSION", parts[0])
            core.exportVariable("MINOR_VERSION", parts[0]+"."+parts[1])
            core.exportVariable("FULL_VERSION", version)

      # Login to the ghcr (github container registry)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Create and publish a docker image
      - name: Setup QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3

      # This can be omitted once runner images have a version of Skopeo > 1.4.1
      # See https://github.com/containers/skopeo/issues/1874 (and https://github.com/devcontainers/ci/issues/191#issuecomment-1416384710)
      - name: Update skopeo
        run: |
          sudo apt purge buildah golang-github-containers-common podman skopeo
          sudo apt autoremove --purge
          REPO_URL="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable"
          source /etc/os-release
          sudo sh -c "echo 'deb ${REPO_URL}/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list"
          sudo wget -qnv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
          sudo apt-key add Release.key
          sudo apt-get update
          sudo apt-get install skopeo

      - name: Build '${{ matrix.image }}' image and push
        uses: devcontainers/ci@v0.3
        with:
          noCache: true
          push: always
          subFolder: "src/${{ matrix.image }}"
          platform: "${{ env.IMAGE_PLATFORM }}"
          imageName: "${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ matrix.image }}"
          imageTag: "${{ env.MAJOR_VERSION }},${{ env.MINOR_VERSION }},${{ env.FULL_VERSION }},latest"
```

and this is a sample of dockerfile

```
# syntax=docker/dockerfile:1

FROM --platform=${BUILDPLATFORM} mcr.microsoft.com/devcontainers/base:bookworm

# update package lists and install inotify-tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends inotify-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
```

please note the usage of `FROM --platform=${BUILDPLATFORM}` which is important

**Comment by mjquinlan2000** [comment]
I'm proofing out some work with eventstore for my job (love it!) and needed a multi-arch image. We use docker compose locally and half the devs are on Mac Intel while the other half are on Apple Silicon. I created a multi-arch manifest that points to 24.2 and the latest alpha arm64 release https://hub.docker.com/r/mjquinlan2000/eventstore

It's working great for development.

**Comment by alexeyzimarev** [comment]
For my work, I use Testcontainers and it's quite trivial to decide on what image to use based on the OS architecture.
https://github.com/Eventuous/eventuous/blob/e42cac3453dd13a809b4f49f2d76a203f52e3324/src/EventStore/test/Eventuous.Tests.EventStore/Fixtures/EsdbContainer.cs

**Comment by itgram** [comment]
```yaml
name: Create and Push Multi-Architecture Docker Image

on:
  push:
    branches:
      - main

jobs:
  create-and-push-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull existing amd64 image
        run: |
          docker pull eventstore/eventstore:24.2.0

      - name: Pull existing arm64 image
        run: |
          docker pull eventstore/eventstore:24.2.0-alpha-arm64v8

      - name: Create and push multi-architecture manifest
        run: |
          docker manifest create eventstore/eventstore:24.2.0-multi-arch \
            eventstore/eventstore:24.2.0 \
            eventstore/eventstore:24.2.0-alpha-arm64v8
          docker manifest annotate eventstore/eventstore:24.2.0-multi-arch eventstore/eventstore:24.2.0 --os linux --arch amd64
          docker manifest annotate eventstore/eventstore:24.2.0-multi-arch eventstore/eventstore:24.2.0-alpha-arm64v8 --os linux --arch arm64
          docker manifest push eventstore/eventstore:24.2.0-multi-arch
```

thanks @mjquinlan2000 for the inspiration

cc: @alexeyzimarev
