### ISSUE TITLE
Volumes / directories used ?

### ISSUE THREAD

**Issue by iangregsondev** [EventStore/EventStore#2425]
Hi,

I have set myself up a small docker-compose and I checked the documentation on docker hub but i couldn't find any information about the location of files.

I would like to create myself a volume so that if my container gets deleted then the data is safe :-)

But I don't know what is being used, anybody knows?

I have so far, but it's missing the volumes :-( The container does work but no named volumes mean my data will disappear when the container is destroyed.

```
version: '3.7'

services:
  eventstore:
    image: eventstore/eventstore

#    volumes:
#    - eventstore-data:/data ????????

    ports:
    - "2113:2113"
    - "1113:1113"

    networks:
    - traefik


    deploy:
      restart_policy:
        condition: on-failure


```
