### ISSUE TITLE
System.UnauthorizedAccessException running EventStore 20.6.1 on Kubernetes

### ISSUE THREAD

**Issue by kollerdroid** [EventStore/EventStore#2808]
The same error in Kubernetes StatefulSet:
```cs
System.UnauthorizedAccessException: Access to the path 'var/lib/eventstore/writer.chk' is denied.
// ...
```
Tested images:
- eventstore/eventstore:latest
- eventstore/eventstore:20.6.1-buster-slim

```yaml
 # ...
apiVersion: apps/v1
kind: StatefulSet
 # ...
          volumeMounts:
            - name: my-eventstore-data
              mountPath: /var/lib/eventstore
 # ...
  volumeClaimTemplates:
    - metadata:
        name: my-eventstore-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 5Gi
 # ...
```

Behind the default _**StorageClass**_ there is a dynamic storage provisioner (_**csi.vsphere.vmware.com**_), which works fine.

_Originally posted by @kollerdroid in https://github.com/EventStore/EventStore/issues/2706#issuecomment-769226716_

**Comment by kristapsstrals** [comment]
Had a similar issue when deploying ES on K8s. Figured that this was due to ES v20.x docker container running as non-root user by default (as opposed to older ES 5.x docker images). To fix this, you need to specify a [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) on k8s pod in the stateful set:

```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: 1000
```

**Comment by danhawkins** [comment]
I also have the same issue :(

**Comment by alexeyzimarev** [comment]
For me, it was the security context. This one works in our env.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: acl-eventstore
  namespace: subs
  labels:
    app: acl
    component: acl-eventstore
    release: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acl
      component: acl-eventstore
      release: production
  template:
    metadata:
      namespace: subs
      labels:
        app: acl
        component: acl-eventstore
        release: production
    spec:
      volumes:
        - name: esdb-config
          configMap:
            name: acl-esdb-config
            defaultMode: 420
        - name: esdb-data
          persistentVolumeClaim:
            claimName: acl-esdb-data
      containers:
        - name: acl-eventstore
          image: 'eventstore/eventstore:21.2.0-buster-slim'
          ports:
            - name: eventstore
              containerPort: 2113
              protocol: TCP
          volumeMounts:
            - name: esdb-config
              mountPath: /etc/eventstore
            - name: esdb-data
              mountPath: /var/lib/eventstore
          livenessProbe:
            httpGet:
              path: health/live
              port: 2113
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: health/live
              port: 2113
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 1000
  serviceName: esdb
```

**Comment by alenagy** [comment]
Unfortunately its still not working for me. Setting securityContext at the container level or at the spec level didn't changed the error.

**Comment by alexeyzimarev** [comment]
My cluster is GKE. The original message says it's VSphere CSI provider. Every CSI provider is different. If you use the NFS provider, or a local hostpath, you get a volume with permissions set by the OS, which none of the workloads could use. Those workloads that run as root can probably run ok, but no one wants those workloads as they are insecure.

It's hard to impossible to diagnose a specific persistent volume issue without having access to the cluster. I would suggest talking to the kubernetes cluster admin, as it's not  ESDB issue, it just needs access to the volume, that's all.

**Comment by alenagy** [comment]
What's weird for me is that I also have a RabbitMQ running there and was able to solve the access issue assigning permissions on the volume folders to the rabbitmq user.
If it's an issue with my AKS cluster and volume permissions then why was RabbitMQ able to work with it but not ESDB?.

**Comment by alenagy** [comment]
And here's the YAML of my StatefulSet

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-dev
  namespace: dev
spec:
  replicas: 1
  serviceName: eventstore-dev
  selector:
    matchLabels:
      app: eventstore-dev
  template:
    metadata:
      labels:
        app: eventstore-dev
    spec:
      containers:
      - name: eventstore-dev
        image: eventstore/eventstore:21.2.0-buster-slim
        ports:
          - containerPort: 1113
          - containerPort: 2113
        env:
          - name: EVENTSTORE_CLUSTER_SIZE
            value: "1"
          - name: EVENTSTORE_RUN_PROJECTIONS
            value: All
          - name: EVENTSTORE_START_STANDARD_PROJECTIONS
            value: "true"
          - name: EVENTSTORE_EXT_TCP_PORT
            value: "1113"
          - name: EVENTSTORE_EXT_HTTP_PORT
            value: "2113"
          - name: EVENTSTORE_INSECURE
            value: "true"
          - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
            value: "true"
          - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
            value: "true"
        volumeMounts:
        - mountPath: /var/lib/eventstore
          name: eventstore-dev-data
        - mountPath: /var/log/eventstore
          name: eventstore-dev-logs
      securityContext:
        fsGroup: 1000
      volumes:
        - name: eventstore-dev-data
          hostPath:
            path: /data/eventstore-dev
            type: DirectoryOrCreate
        - name: eventstore-dev-logs
          hostPath:
            path: /logs/eventstore-dev
            type: DirectoryOrCreate
```
