### ISSUE TITLE
Documentation is a complete hell.

### ISSUE THREAD

**Issue by TanvirArjel** [EventStore/EventStore#2996]
I have spent a lot of time but did not find any clear instruction on how to run EventStore on windows 10 with all the admin UI menu items enabled. This is a very popular technology but the documentation is quite poor. 

This is what I have been able to achieve after spending a lot of time.

![Web capture_18-6-2021_18137_localhost](https://user-images.githubusercontent.com/14342773/122559263-ed345600-d060-11eb-8b27-61f8a1616818.jpeg)

Please tell me how can I enable all the UI menu items with a yaml configuration file. Here is my configuration file:

```
CertificateStoreLocation: CurrentUser
CertificateStoreName: My
CertificateThumbPrint: E9136AB728CC9C497C7F5C771047254B13BE8414
CertificateSubjectName: CN=eventstore.com
ExtSecureTcpPort: 1115
```

**Comment by ylorph** [comment]
This shoud help you set it up as you want:
https://developers.eventstore.com/server/v21.2/docs/installation/#configuration-wizard

**Comment by TanvirArjel** [comment]
@ylorph This is not event helpful with clear instructions.

What should be the values of these:

![image](https://user-images.githubusercontent.com/14342773/122562222-a6e0f600-d064-11eb-8b8f-af234d7167ea.png)

![image](https://user-images.githubusercontent.com/14342773/122562266-b3654e80-d064-11eb-9de1-392d6796562d.png)

![image](https://user-images.githubusercontent.com/14342773/122562302-bbbd8980-d064-11eb-9746-7fd744513134.png)

**Comment by ylorph** [comment]
All depends if you want a cluster or not, what kind of networking etc... 

https://discuss.eventstore.com/  might be a better place to ask

**Comment by TanvirArjel** [comment]
@ylorph Here is my updated config but still not working:

```
# Paths
Db: C:\EventStore\Data
Index: C:\EventStore\Index
Log: C:\EventStore\Logs

# Certificates configuration
CertificateStoreLocation: CurrentUser
CertificateStoreName: My
CertificateThumbPrint: E9136AB728CC9C497C7F5C771047254B13BE8414
CertificateSubjectName: CN=eventstore.com

# Network configuration
HttpPort: 2113
IntTcpPort: 1112
ExtTcpPort: 1113
EnableExternalTcp: true
EnableAtomPubOverHTTP: true

# Projections configuration
RunProjections: All
```

**Comment by ylorph** [comment]
I would advise you have a look at the TLS configuration section: it can be tricky to get right 
https://developers.eventstore.com/server/v21.2/docs/security/configuration.html#certificates-configuration

**Comment by alexeyzimarev** [comment]
"UI menu items" for projections and stream browser require that you enable the projections engine and the Atom Feed protocol, which are both disabled by default. As you are using the configurator, both options are by default enabled, and the configuration you get from it should be correct.

<img width="983" alt="Screenshot 2021-06-19 at 17 41 02" src="https://user-images.githubusercontent.com/2821205/122647685-c1c76f00-d125-11eb-814d-1aac7158599b.png">

**Comment by alexeyzimarev** [comment]
I just used the configuration in the docs to generate the config file for Windows, with all the instructions. That's the configuration file I got:

```yaml
---
# Paths
Db: C:\ESDB\Data
Index: C:\ESDB\Index
Log: C:\ESDB\Logs

# Certificates configuration
CertificateFile: C:\ESDB\certs\node.crt
CertificatePrivateKeyFile: C:\ESDB\certs\node.key
TrustedRootCertificatesPath: C:\ESDB\certs\ca

# Network configuration
IntIp: 0.0.0.0
ExtIp: 0.0.0.0
HttpPort: 2113
IntTcpPort: 1112
ExtTcpPort: 1113
EnableExternalTcp: true
EnableAtomPubOverHTTP: true

# Projections configuration
RunProjections: All
```

As I am the one who made the configuration, I'd really like to know why is it "hell". I struggle to see an issue with the configuration it generates, and where you got your config settings from.
