### ISSUE TITLE
GRPC endpoint doesn't appear to honour authentication

### ISSUE THREAD

**Issue by ChrisMcKee** [EventStore/EventStore#3411]
**Describe the bug**
Connecting via GRPC connection string to an evenstoredb with credentials; the client connects and writes to eventstore ignoring all auth.

Connecting using `"esdb://teamname-test-eventstore-svc.infra.svc.cluster.local:2113?keepAliveTimeout=10000&keepAliveInterval=10000"` behaves the same as connecting with Connecting using `"esdb://admin:changeit@teamname-test-eventstore-svc.infra.svc.cluster.local:2113?keepAliveTimeout=10000&keepAliveInterval=10000"`

The UI acknowledges and still requires credentials to http auth is working as expected.
The GRPC Client seems to just plow straight through. 

Eventstore Config File

```yaml
---
# Paths
Db: /var/lib/eventstore
Index: /var/lib/eventstore/index
Log: /var/log/eventstore

CertificateFile: /etc/eventstore/certs/node.crt
CertificatePrivateKeyFile: /etc/eventstore/certs/node.key
TrustedRootCertificatesPath: /etc/eventstore/certs/ca

# Network configuration
IntIp: 0.0.0.0
ExtIp: 0.0.0.0
HttpPort: 2113
IntTcpPort: 1112
EnableExternalTcp: false
EnableAtomPubOverHTTP: true

# Projections configuration
RunProjections: All
```

Kube Environment Variables

```yaml
      containers:
      - env:
        - name: EVENTSTORE_START_STANDARD_PROJECTIONS
          value: "true"
        - name: EVENTSTORE_RUN_PROJECTIONS
          value: All
        - name: EVENTSTORE_WRITE_STATS_TO_DB
          value: "false"
        - name: EVENTSTORE_INT_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: EVENTSTORE_EXT_IP
          value: 0.0.0.0
        - name: EVENTSTORE_EXT_IP_ADVERTISE_AS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: EVENTSTORE_CLUSTER_SIZE
          value: "1"
        - name: EVENTSTORE_EXT_HOST_ADVERTISE_AS
          value: teamname-test-eventstore-svc.infra.svc.cluster.local
```

```cs
using System.Text.Json;
using EventStore.Client;

var settings = new EventStoreClientSettings
{
    CreateHttpMessageHandler = () =>
        new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback =
                (sender, cert, chain, sslPolicyErrors) => true
        },
    ConnectivitySettings = {
                    Address = new Uri("esdb://admin:changeit@teamname-test-eventstore-svc.infra.svc.cluster.local:2113?keepAliveTimeout=10000&keepAliveInterval=10000")
                }
};

var client = new EventStoreClient(settings);


var evt = new
{
    EntityId = Guid.NewGuid().ToString("N"),
    ImportantData = "I wrote my first event!"
};

var eventData = new EventData(
    Uuid.NewUuid(),
    "TestEvent",
    JsonSerializer.SerializeToUtf8Bytes(evt)
);

await client.AppendToStreamAsync(
    "some-stream",
    StreamState.Any,
    new[] { eventData }
);

```

```shell
/opt/eventstore$ ./eventstored --what-if
[26978, 1,11:14:42.102,INF] 
"ES VERSION:"             "20.10.5.0" ("tags/oss-v20.10.5"/"e81250a5e", "Thu, 9 Dec 2021 14:10:21 +0100")
[26978, 1,11:14:42.117,INF] "OS:"                     Linux ("Unix 5.4.172.90")
[26978, 1,11:14:42.118,INF] "RUNTIME:"                ".NET 5.0.12/7211aa01b" (64-bit)
[26978, 1,11:14:42.118,INF] "GC:"                     "3 GENERATIONS"
[26978, 1,11:14:42.118,INF] "LOGS:"                   "/var/log/eventstore"
[26978, 1,11:14:42.131,INF] MODIFIED OPTIONS:

        WHAT IF:                  True (Command Line)
        START STANDARD PROJECTIONS: true (Environment Variable)
        INT IP:                   10.22.3.170 (Environment Variable)
        EXT IP:                   0.0.0.0 (Environment Variable)
        EXT HOST ADVERTISE AS:    teamname-test-eventstore-svc.infra.svc.cluster.local (Environment Variable)
        INT HOST ADVERTISE AS:    localhost (Environment Variable)
        CLUSTER SIZE:             1 (Environment Variable)
        RUN PROJECTIONS:          All (Environment Variable)
        WRITE STATS TO DB:        false (Environment Variable)
        DB:                       /var/lib/eventstore (Config File)
        INDEX:                    /var/lib/eventstore/index (Config File)
        LOG:                      /var/log/eventstore (Config File)
        CERTIFICATE FILE:         /etc/eventstore/certs/node.crt (Config File)
        CERTIFICATE PRIVATE KEY FILE: /etc/eventstore/certs/node.key (Config File)
        TRUSTED ROOT CERTIFICATES PATH: /etc/eventstore/certs/ca (Config File)
        HTTP PORT:                2113 (Config File)
        INT TCP PORT:             1112 (Config File)
        ENABLE EXTERNAL TCP:      false (Config File)
        ENABLE ATOM PUB OVER HTTP: true (Config File)

DEFAULT OPTIONS:

        CONFIG:                   /etc/eventstore/eventstore.conf (<DEFAULT>)
        HELP:                     False (<DEFAULT>)
        VERSION:                  False (<DEFAULT>)
        LOG LEVEL:                Default (<DEFAULT>)
        LOG CONSOLE FORMAT:       Plain (<DEFAULT>)
        LOG FILE RETENTION COUNT: 31 (<DEFAULT>)
        DISABLE LOG FILE:         False (<DEFAULT>)
        LOG CONFIG:               logconfig.json (<DEFAULT>)
        DISABLE HTTP CACHING:     False (<DEFAULT>)
        EXT TCP PORT:             1113 (<DEFAULT>)
        ADVERTISE HOST TO CLIENT AS: <empty> (<DEFAULT>)
        ADVERTISE HTTP PORT TO CLIENT AS: 0 (<DEFAULT>)
        ADVERTISE TCP PORT TO CLIENT AS: 0 (<DEFAULT>)
        EXT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        HTTP PORT ADVERTISE AS:   0 (<DEFAULT>)
        INT TCP PORT ADVERTISE AS: 0 (<DEFAULT>)
        INT TCP HEARTBEAT TIMEOUT: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT TIMEOUT: 1000 (<DEFAULT>)
        INT TCP HEARTBEAT INTERVAL: 700 (<DEFAULT>)
        EXT TCP HEARTBEAT INTERVAL: 2000 (<DEFAULT>)
        GOSSIP ON SINGLE NODE:    False (<DEFAULT>)
        CONNECTION PENDING SEND BYTES THRESHOLD: 10485760 (<DEFAULT>)
        CONNECTION QUEUE SIZE THRESHOLD: 50000 (<DEFAULT>)
        STREAM INFO CACHE CAPACITY: 0 (<DEFAULT>)
        NODE PRIORITY:            0 (<DEFAULT>)
        MIN FLUSH DELAY MS:       2 (<DEFAULT>)
        COMMIT COUNT:             -1 (<DEFAULT>)
        PREPARE COUNT:            -1 (<DEFAULT>)
        DISABLE ADMIN UI:         False (<DEFAULT>)
        DISABLE STATS ON HTTP:    False (<DEFAULT>)
        DISABLE GOSSIP ON HTTP:   False (<DEFAULT>)
        DISABLE SCAVENGE MERGING: False (<DEFAULT>)
        SCAVENGE HISTORY MAX AGE: 30 (<DEFAULT>)
        DISCOVER VIA DNS:         True (<DEFAULT>)
        CLUSTER DNS:              fake.dns (<DEFAULT>)
        CLUSTER GOSSIP PORT:      2113 (<DEFAULT>)
        GOSSIP SEED:              <empty> (<DEFAULT>)
        STATS PERIOD SEC:         30 (<DEFAULT>)
        CACHED CHUNKS:            -1 (<DEFAULT>)
        READER THREADS COUNT:     0 (<DEFAULT>)
        CHUNKS CACHE SIZE:        536871424 (<DEFAULT>)
        MAX MEM TABLE SIZE:       1000000 (<DEFAULT>)
        HASH COLLISION READ LIMIT: 100 (<DEFAULT>)
        MEM DB:                   False (<DEFAULT>)
        SKIP DB VERIFY:           False (<DEFAULT>)
        WRITE THROUGH:            False (<DEFAULT>)
        UNBUFFERED:               False (<DEFAULT>)
        CHUNK INITIAL READER COUNT: 5 (<DEFAULT>)
        PROJECTION THREADS:       3 (<DEFAULT>)
        WORKER THREADS:           0 (<DEFAULT>)
        PROJECTIONS QUERY EXPIRY: 5 (<DEFAULT>)
        FAULT OUT OF ORDER PROJECTIONS: False (<DEFAULT>)
        ENABLE TRUSTED AUTH:      False (<DEFAULT>)
        CERTIFICATE PASSWORD:     <empty> (<DEFAULT>)
        CERTIFICATE STORE LOCATION: <empty> (<DEFAULT>)
        CERTIFICATE STORE NAME:   <empty> (<DEFAULT>)
        CERTIFICATE SUBJECT NAME: <empty> (<DEFAULT>)
        CERTIFICATE RESERVED NODE COMMON NAME: eventstoredb-node (<DEFAULT>)
        CERTIFICATE THUMBPRINT:   <empty> (<DEFAULT>)
        DISABLE INTERNAL TCP TLS: False (<DEFAULT>)
        DISABLE EXTERNAL TCP TLS: False (<DEFAULT>)
        AUTHORIZATION TYPE:       internal (<DEFAULT>)
        AUTHENTICATION TYPE:      internal (<DEFAULT>)
        AUTHORIZATION CONFIG:     <empty> (<DEFAULT>)
        AUTHENTICATION CONFIG:    <empty> (<DEFAULT>)
        DISABLE FIRST LEVEL HTTP AUTHORIZATION: False (<DEFAULT>)
        PREPARE TIMEOUT MS:       2000 (<DEFAULT>)
        COMMIT TIMEOUT MS:        2000 (<DEFAULT>)
        WRITE TIMEOUT MS:         2000 (<DEFAULT>)
        UNSAFE DISABLE FLUSH TO DISK: False (<DEFAULT>)
        UNSAFE IGNORE HARD DELETE: False (<DEFAULT>)
        SKIP INDEX VERIFY:        False (<DEFAULT>)
        INDEX CACHE DEPTH:        16 (<DEFAULT>)
        OPTIMIZE INDEX MERGE:     False (<DEFAULT>)
        GOSSIP INTERVAL MS:       2000 (<DEFAULT>)
        GOSSIP ALLOWED DIFFERENCE MS: 60000 (<DEFAULT>)
        GOSSIP TIMEOUT MS:        2500 (<DEFAULT>)
        LEADER ELECTION TIMEOUT MS: 1000 (<DEFAULT>)
        READ ONLY REPLICA:        False (<DEFAULT>)
        UNSAFE ALLOW SURPLUS NODES: False (<DEFAULT>)
        ENABLE HISTOGRAMS:        False (<DEFAULT>)
        LOG HTTP REQUESTS:        False (<DEFAULT>)
        LOG FAILED AUTHENTICATION ATTEMPTS: False (<DEFAULT>)
        ALWAYS KEEP SCAVENGED:    False (<DEFAULT>)
        SKIP INDEX SCAN ON READS: False (<DEFAULT>)
        REDUCE FILE CACHE PRESSURE: False (<DEFAULT>)
        INITIALIZATION THREADS:   1 (<DEFAULT>)
        MAX AUTO MERGE INDEX LEVEL: 2147483647 (<DEFAULT>)
        MAX TRUNCATION:           268435456 (<DEFAULT>)
        MAX APPEND SIZE:          1048576 (<DEFAULT>)
        INSECURE:                 False (<DEFAULT>)
        DEAD MEMBER REMOVAL PERIOD SEC: 1800 (<DEFAULT>)
        KEEP ALIVE INTERVAL:      10000 (<DEFAULT>)
        KEEP ALIVE TIMEOUT:       10000 (<DEFAULT>)

[26978, 1,11:14:42.133,WRN] DEPRECATED
- AtomPub over HTTP Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead.
```

![image](https://user-images.githubusercontent.com/83597/151962808-d8f653ec-83bd-436f-8655-e041839d22db.png)
