### ISSUE TITLE
What is the recommended way to "browse" the streams, or do I have to write queries to get the data out?

### ISSUE THREAD

**Issue by OliWinter** [EventStore/EventStore#3455]
What is the recommended way to "browse" the streams, or do I have to write queries to get the data out?

_Originally posted by @mastoj in https://github.com/EventStore/EventStore/issues/2640#issuecomment-962988628_

**Comment by OliWinter** [comment]
I reopen this issue, because in v21.06 I'm unable to set 'ENABLE_ATOM_PUB_OVER_HTTP: true'

Or what am I doing wrong ??

**Comment by OliWinter** [comment]
Sorry, my fault...
I forgot the 'EVENTSTORE_' prefix.

Now it works.

**Comment by tqwewe** [comment]
Where do you set `ENABLE_ATOM_PUB_OVER_HTTP`? And did you mean it should be EVENTSTORE__ENABLE_ATOM_PUB_OVER_HTTP`?

**Comment by blindlobstar** [comment]
> Where do you set `ENABLE_ATOM_PUB_OVER_HTTP`? And did you mean it should be `EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP`?

You can set this with environment variable: `EVENTSTORE_EnableAtomPubOverHttp`. Here is an example of docker-compose configuration:
```
version: "3.4"

services:
  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_EnableAtomPubOverHttp=true
    ports:
      - "2113:2113"
      - "1113:1113"
```
