### ISSUE TITLE
HTTP 1.1 is not supported

### ISSUE THREAD

**Issue by MKaramen** [EventStore/EventStore#4080]
**Describe the bug**
I'm trying to expose my event-store-pod through a k8s ingress. I have access to the admin dashboard but when I try to connect my application I get the following error :

![image](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/4c41d584-867a-4bd5-9071-8fa579eb80c1/8fa1985a-f146-4908-af02-32a2aea03dcf)

Client:  Event-store-java-client
Docker image: Latest
Connection string: `esdb://my.custom.domain?tls=false`

Here is the configuration for my ingress :

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  labels:
    app: event-store
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: event-store-service
                port:
                  number: 2113
```

Connection string in my  java app :

```
EventStoreDBClientSettings settings = EventStoreDBConnectionString.parseOrThrow("esdb://my.custom.domain?tls=false");
EventStoreDBClient client = EventStoreDBClient.create(settings);
```

Now if i go to `http://my.custom.domain` I have access to the admin dashboard. It seems like the http is working but not the grpc.

The issue seems similar to #2707

<sub>[DB-547](https://linear.app/eventstore/issue/DB-547/http-11-is-not-supported)</sub>
