### ISSUE TITLE
Incorrect stream name in UI for the first event

### ISSUE THREAD

**Issue by MaximKitsenko** [EventStore/EventStore#4150]
**Describe the bug**
`.net7`, `EventStore 23.10.0-jammy`. Application massively sends event to EventStore.  The first event in StreamBrowser has stream `Tenant-0`.
But in UI it showed like stream `Tenant-1483864`. If User clicks on stream `Tenant-1483864` UI says there is no events in stream. If user clicks on `JSON` link he can see body of event.
But if user puts in URL `Tenant-0` he will se correct stream.

Strange thing - if application sends messages slowly - bug disappear.

**To Reproduce**

1. Create at least 1000 events one by one in a loop, like `tenant-0 Created`, `tenant-1 Created`
   etc2.
2. Go to UI, `/web/index.html#/streams/$all`,
3. Press `last` to seethe 1st event

**Expected behavior** User should see a list of Streams starting from 0 like

```
[0@tenant-18]
[0@tenant-17]
...
[0@tenant-1]
[0@tenant-0]
[0@$$$scavenges]

Actual behavior

User should see a list of Streams starting from 1483864 like
[0@tenant-18]
[0@tenant-17]
...
[0@tenant-1]
[0@tenant-1483864]
[0@$$$scavenges]
```

**Config/Logs/Screenshots**
docker yaml:

```
event-store2:     
  image: eventstore/eventstore:23.10.0-jammy
     #volumes:
     #  - eventstore:/var/lib/eventstore23
     ports:
       - 7114:1113
       - 8114:2113
      environment: 
       EVENTSTORE_RUN_PROJECTIONS: None
       EVENTSTORE_CONNECTION_PENDING_SEND_BYTES_THRESHOLD: 104857600
       EVENTSTORE_INT_TCP_HEARTBEAT_TIMEOUT: 5000
       EVENTSTORE_INSECURE: "true"
       EVENTSTORE_ENABLEATOMPUBOVERHTTP: "true"
       EVENTSTORE_MEM_DB: "True"  `
```

![Безымянный](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/af3a140c-6074-4a40-ab7a-7c8d0314216f/703adc81-2e2b-4a80-a322-f619f866a8e6)

![image](https://uploads.linear.app/a2a29b63-594b-4491-8437-5f7f43da2367/1c7f5f6d-033e-4252-bfb5-829fd4d3187f/52d838c1-67f2-48dc-947c-ee085e33af7a)

**EventStore details**

* EventStore server version: 23.10.0-jammy
* Operating system:
* EventStore client library and version (if applicable): EventStore.Client.Grpc.Streams 23.1.0

**Additional context**

<sub>[DB-662](https://linear.app/eventstore/issue/DB-662/incorrect-stream-name-in-ui-for-the-first-event)</sub>
