### ISSUE TITLE
Default admin password cannot be changed

### ISSUE THREAD

**Issue by brunocascio** [EventStore/EventStore#4318]
**Describe the bug**
Evenstore thrown an exception when a different default admin password is passed through configuration when a new cluster is created.

```
Cannot set default admin password when not using the internal authentication.
```

**To Reproduce**

Run the following manifest:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: myevs
  name: myevs
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: myevs
  serviceName: myevs
  template:
    metadata:
      labels:
        app: myevs
    spec:
      containers:
        - name: eventstore
          env:
            - name: EVENTSTORE_INSECURE
              value: 'true'
            - name: EVENTSTORE_DEFAULT_ADMIN_PASSWORD
              value: mypass
          image: 'eventstore/eventstore:24.2.0-alpha-arm64v8'
```

**Expected behavior**
Admin password should be configured with the env variable provided instead of fail.

**Actual behavior**
An error "Cannot set default admin password when not using the internal authentication." is thrown and pod does not start.

**EventStore details**
 - EventStore server version: 24.2.0

 - Operating system: OSX with docker and minikube

**Additional context**
